experimental APB
fusor/apb-examples pull request #100
Opened 2017-08-07 12:32 UTC by shawn-hurley

* Implements bind and unbind action
* The user can determine how they want the APB  to behave in managing users

2017-08-11 03:10 UTC, LorbusChris commented on experimental/rhscl-postgresql-apb/roles/unbind-rhscl-postgresql-apb-openshift/tasks/main.yml
> +- name: remove owner privillages on database
nit: privileges

2017-08-11 14:18 UTC, rthallisey requested changes

2017-08-11 14:18 UTC, rthallisey commented on experimental/rhscl-postgresql-apb/roles/rhscl-postgresql-apb-openshift/tasks/main.yml
> +  shell: 'echo "{\"POSTGRESQL_HOST\": \"postgresql\", \"POSTGRESQL_PORT\": \"5432\", \"POSTGRESQL_USER\": \"{{ generated_user }}\", \"POSTGRESQL_PASSWORD\": \"{{ generated_password }}\", \"POSTGRESQL
Can you use the ```asb_encode_binding:``` module instead.

2017-08-11 14:18 UTC, rthallisey commented on experimental/rhscl-postgresql-apb/README.md
> +* Deploys 1 postgresql container.
Can you be a little more descriptive as to why this is different than rhscl-postgresql-apb? We want to make sure the user understands the feature demonstrated by this playbook.

2017-08-17 12:46 UTC, rthallisey approved these changes

2017-08-22 15:43 UTC, jwmatthews commented on experimental/bind-rhscl-postgresql-apb/README.md
> +`docker run -e "OPENSHIFT_TARGET=<openshift_target>" -e "OPENSHIFT_USER=<user>" -e "OPENSHIFT_PASS=<password>" ansibleplaybookbundle/rhscl-postgresql-apb provision`
maybe change this example since the name is now different?

2017-08-22 15:44 UTC, jwmatthews commented on experimental/bind-rhscl-postgresql-apb/README.md
> +`docker run -e "OPENSHIFT_TARGET=<openshift_target>" -e "OPENSHIFT_USER=<user>" -e "OPENSHIFT_PASS=<password>" ansibleplaybookbundle/rhscl-postgresql-apb deprovision`
same here

2017-08-22 15:48 UTC, dymurray commented on experimental/bind-rhscl-postgresql-apb/README.md
> +`docker run -e "OPENSHIFT_TARGET=<openshift_target>" -e "OPENSHIFT_USER=<user>" -e "OPENSHIFT_PASS=<password>" ansibleplaybookbundle/rhscl-postgresql-apb provision`
This also needs to be updated to use OPENSHIFT_TOKEN instead of user/pass

2017-08-22 15:48 UTC, dymurray commented on experimental/bind-rhscl-postgresql-apb/README.md
> +`docker run -e "OPENSHIFT_TARGET=<openshift_target>" -e "OPENSHIFT_USER=<user>" -e "OPENSHIFT_PASS=<password>" ansibleplaybookbundle/rhscl-postgresql-apb deprovision`
same as above

2017-08-23 13:54 UTC, merged